### ISSUE TITLE
SDK with java 8 (OpenJDK 1.8)

### ISSUE THREAD

**Issue by dracoon-support** [dracoon/dracoon-java-sdk#10]
I have downloaded the Java SDK from Github. However, the SDK is designed for Java 11. Unfortunately, our Abas Server only supports Java 8 (OpenJDK 1.8).

I set up the project manually, but I still receive an error from the JRE:

"java.lang.UnsupportedClassVersionError: com/dracoon/sdk/Log has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0."

I'm unable to make progress on this issue and hope you can assist me.

**Comment by mkellnhofer** [comment]
Sorry, we no longer support Java 8 since version 3.0.0.

See: [Minimum Requirements](https://github.com/dracoon/dracoon-java-sdk?tab=readme-ov-file#minimum-requirements)
