### ISSUE TITLE
log message mixup

### ISSUE THREAD

**Issue by Crow08** [dracoon/dracoon-java-sdk#6]
Just a small nitpick, the log messages on the following lines should be switched:

https://github.com/dracoon/dracoon-java-sdk/blob/eae4424c3222996209d6948b617abd6538e5f1ff/example/src/main/java/com/dracoon/sdk/example/DracoonExamples.java#L493

https://github.com/dracoon/dracoon-java-sdk/blob/eae4424c3222996209d6948b617abd6538e5f1ff/example/src/main/java/com/dracoon/sdk/example/DracoonExamples.java#L498

**Comment by mkellnhofer** [comment]
Thanks! Will be fixed in the next release.
